name: Pylint Check

on:
  push:
    branches:
      - main  

jobs:
  lint:
    name: Run Pylint
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        
    - name: Run Pylint on app.py
      run: pylint app.py

    - name: Run Pylint on model.py
      run: pylint model.py

    - name: Upload Pylint report
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: pylint-report
        path: pylint-report.txt
