name: Python Lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Change this to your desired Python version

    - name: Install dependencies
      run: pip install -r requirements.txt  # If you have a requirements file

    - name: Run linting
      run: python lint.py

