name: Pylint

on:
  push:
    branches:
      - main  # Change this to the branch you want to monitor

jobs:
  lint:
    name: Run Pylint
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # You can change this to your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
      # You can add more dependencies installation if needed

    - name: Run Pylint
      run: pylint Flask_Image_Recignition  # Replace 'your_module_or_directory' with your specific module or directory

    - name: Upload Pylint report
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: pylint-report
        path: pylint-report.txt

